version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    timezone: UCT
  open-pull-requests-limit: 99
  reviewers:
  - kkleemola, pwnbus
  assignees:
  - kkleemola, pwnbus
  ignore:
  - dependency-name: golang
    versions:
    - ">= 1.17"
- package-ecosystem: docker
  directory: "/database"
  schedule:
    interval: monthly
    timezone: UCT
  open-pull-requests-limit: 99
  reviewers:
  - kkleemola, pwnbus
  ignore:
  - dependency-name: postgres
    versions:
    - ">= 12.a"
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: monthly
    day: sunday
    timezone: UCT
  open-pull-requests-limit: 99
  reviewers:
  - kkleemola, pwnbus
- package-ecosystem: gomod
  directory: "/tools/autograph-monitor"
  schedule:
    interval: monthly
    day: sunday
    timezone: UCT
  open-pull-requests-limit: 99
  reviewers:
  - kkleemola, pwnbus
  assignees:
  - kkleemola, pwnbus
